set(PACKAGE_CONFIG_TEXT "Avisynth include directory")

if(WIN32)
    if(DEFINED ENV{AVISYNTH_SDK_PATH})
        set(AVS_SDK_FOLDER $ENV{AVISYNTH_SDK_PATH})
        string(REGEX REPLACE "\\\\" "/" AVS_SDK_FOLDER ${AVS_SDK_FOLDER})
        set(AVS_INCLUDE_DIR "${AVS_SDK_FOLDER}/include" CACHE PATH "${PACKAGE_CONFIG_TEXT}")
    endif()
else()
    find_path(AVS_INCLUDE_PREFIX NAMES avisynth PATHS usr PATH_SUFFIXES include)
    if(AVS_INCLUDE_PREFIX)
        set(AVS_INCLUDE_DIR "${AVS_INCLUDE_PREFIX}/avisynth" CACHE PATH ${PACKAGE_CONFIG_TEXT})
    endif()
endif()

if(AVS_INCLUDE_DIR)
    set(Avisynth_FOUND True)
    message(STATUS "${PACKAGE_CONFIG_TEXT}: ${AVS_INCLUDE_DIR}")
    set(ENABLE_AVISYNTH ON)
else()
    set(Avisynth_FOUND False)
    set(AVS_INCLUDE_DIR "AVS_INCLUDE_DIR-NOTFOUND" CACHE PATH "${PACKAGE_CONFIG_TEXT}")
    message(STATUS "${PACKAGE_CONFIG_TEXT} NOT found")
    set(ENABLE_AVISYNTH OFF)
endif()
